import type { CategoryKind, ProductAttributes } from '@vellor/shared';

/**
 * Catálogo de demonstração. Todos os produtos são placeholders marcados com o
 * atributo `_placeholder` e devem ser substituídos pelo catálogo real no Admin.
 */

export interface SeedCategory {
  slug: string;
  name: string;
  kind: CategoryKind;
  description: string;
  position: number;
  collections: Array<{ slug: string; name: string; description: string }>;
}

export interface SeedVariant {
  sku: string;
  name: string;
  priceCents?: number;
  stockQuantity: number;
  optionValues?: Record<string, string>;
}

export interface SeedProduct {
  slug: string;
  name: string;
  brand: string;
  categorySlug: string;
  collectionSlug: string;
  priceCents: number;
  compareAtPriceCents?: number;
  shortDescription: string;
  description: string;
  isFeatured?: boolean;
  isNew?: boolean;
  isBestseller?: boolean;
  attributes: ProductAttributes;
  weightGrams: number;
  dims: [number, number, number];
  variants: SeedVariant[];
}

export const SEED_CATEGORIES: SeedCategory[] = [
  {
    slug: 'relogios',
    name: 'Relógios',
    kind: 'watch',
    description: 'Peças de alta relojoaria selecionadas com autenticidade garantida.',
    position: 1,
    collections: [
      {
        slug: 'cronografos',
        name: 'Cronógrafos',
        description: 'Complicação de cronógrafo para quem mede o tempo com precisão.',
      },
      {
        slug: 'classicos',
        name: 'Clássicos',
        description: 'Relógios de vestir, finos e atemporais.',
      },
      {
        slug: 'esportivos-e-divers',
        name: 'Esportivos e Divers',
        description: 'Resistência e legibilidade para qualquer aventura.',
      },
      {
        slug: 'ouro-e-metais-nobres',
        name: 'Ouro e Metais Nobres',
        description: 'Caixas em ouro, platina e ligas preciosas.',
      },
      {
        slug: 'alta-relojoaria',
        name: 'Alta Relojoaria',
        description: 'Grandes complicações e edições limitadas.',
      },
    ],
  },
  {
    slug: 'perfumes',
    name: 'Perfumes de Nicho',
    kind: 'perfume',
    description: 'Casas de perfumaria autoral com matérias-primas raras e concentrações elevadas.',
    position: 2,
    collections: [
      { slug: 'amadeirados', name: 'Amadeirados', description: 'Sândalo, vetiver, cedro e oud.' },
      {
        slug: 'orientais-e-ambar',
        name: 'Orientais e Âmbar',
        description: 'Resinas, especiarias e baunilha.',
      },
      { slug: 'florais', name: 'Florais', description: 'Íris, rosa, jasmim e tuberosa.' },
      {
        slug: 'citricos-e-frescos',
        name: 'Cítricos e Frescos',
        description: 'Bergamota, neroli e notas aquáticas.',
      },
      {
        slug: 'extraits-e-edicoes-especiais',
        name: 'Extraits e Edições Especiais',
        description: 'Concentrações máximas e lançamentos limitados.',
      },
    ],
  },
];

const PLACEHOLDER_NOTE =
  'Produto de demonstração. Substitua nome, descrição, fotos, preço e ficha técnica pelo item real no painel administrativo.';

export const SEED_PRODUCTS: SeedProduct[] = [
  {
    slug: 'cronografo-heritage-aco',
    name: 'Cronógrafo Heritage Aço',
    brand: 'Vellor Sélection',
    categorySlug: 'relogios',
    collectionSlug: 'cronografos',
    priceCents: 2_490_000,
    shortDescription: 'Cronógrafo automático em aço com mostrador azul sunburst e taquímetro.',
    description: PLACEHOLDER_NOTE,
    isFeatured: true,
    isBestseller: true,
    attributes: {
      _placeholder: 'sim',
      reference: 'VS-CH-001',
      movement: 'Automático com cronógrafo',
      calibre: 'VS 4130',
      powerReserve: '72 horas',
      caseMaterial: 'Aço inoxidável 904L',
      caseDiameter: 40,
      caseThickness: 12.4,
      crystal: 'Safira',
      waterResistance: '100 m',
      dialColor: 'Azul sunburst',
      strap: 'Aço com fecho oyster',
      gender: 'Masculino',
      condition: 'Novo',
      boxAndPapers: 'Completo (caixa e certificado)',
      warranty: '2 anos Vellor',
    },
    weightGrams: 900,
    dims: [20, 16, 12],
    variants: [
      {
        sku: 'VS-CH-001-AZ',
        name: 'Mostrador azul',
        stockQuantity: 2,
        optionValues: { Mostrador: 'Azul' },
      },
      {
        sku: 'VS-CH-001-PR',
        name: 'Mostrador preto',
        stockQuantity: 1,
        optionValues: { Mostrador: 'Preto' },
      },
    ],
  },
  {
    slug: 'classico-ultrafino-ouro-rose',
    name: 'Clássico Ultrafino Ouro Rosé',
    brand: 'Vellor Sélection',
    categorySlug: 'relogios',
    collectionSlug: 'classicos',
    priceCents: 4_250_000,
    shortDescription: 'Relógio de vestir ultrafino em ouro rosé 18k com pulseira de jacaré.',
    description: PLACEHOLDER_NOTE,
    isFeatured: true,
    attributes: {
      _placeholder: 'sim',
      reference: 'VS-CL-002',
      movement: 'Corda manual',
      calibre: 'VS 430',
      powerReserve: '48 horas',
      caseMaterial: 'Ouro rosé 18k',
      caseDiameter: 38,
      caseThickness: 6.8,
      crystal: 'Safira',
      waterResistance: '30 m',
      dialColor: 'Prata opalino',
      strap: 'Couro de jacaré marrom',
      gender: 'Unissex',
      condition: 'Novo',
      boxAndPapers: 'Completo (caixa e certificado)',
      warranty: '2 anos Vellor',
    },
    weightGrams: 700,
    dims: [20, 16, 12],
    variants: [{ sku: 'VS-CL-002', name: 'Padrão', stockQuantity: 1 }],
  },
  {
    slug: 'diver-profissional-300m',
    name: 'Diver Profissional 300M',
    brand: 'Vellor Sélection',
    categorySlug: 'relogios',
    collectionSlug: 'esportivos-e-divers',
    priceCents: 1_890_000,
    compareAtPriceCents: 2_100_000,
    shortDescription: 'Mergulhador com bezel cerâmico unidirecional e válvula de hélio.',
    description: PLACEHOLDER_NOTE,
    isBestseller: true,
    attributes: {
      _placeholder: 'sim',
      reference: 'VS-DV-003',
      movement: 'Automático',
      calibre: 'VS 8800',
      powerReserve: '55 horas',
      caseMaterial: 'Aço inoxidável',
      caseDiameter: 42,
      caseThickness: 13.5,
      crystal: 'Safira com antirreflexo',
      waterResistance: '300 m',
      dialColor: 'Preto fosco',
      strap: 'Aço / borracha',
      gender: 'Masculino',
      condition: 'Novo',
      boxAndPapers: 'Completo (caixa e certificado)',
      warranty: '2 anos Vellor',
    },
    weightGrams: 950,
    dims: [20, 16, 12],
    variants: [
      {
        sku: 'VS-DV-003-AC',
        name: 'Pulseira de aço',
        stockQuantity: 3,
        optionValues: { Pulseira: 'Aço' },
      },
      {
        sku: 'VS-DV-003-BR',
        name: 'Pulseira de borracha',
        priceCents: 1_790_000,
        stockQuantity: 2,
        optionValues: { Pulseira: 'Borracha' },
      },
    ],
  },
  {
    slug: 'gmt-viajante-titanio',
    name: 'GMT Viajante Titânio',
    brand: 'Vellor Sélection',
    categorySlug: 'relogios',
    collectionSlug: 'esportivos-e-divers',
    priceCents: 3_120_000,
    shortDescription: 'Segundo fuso horário em caixa de titânio grau 5, leve e resistente.',
    description: PLACEHOLDER_NOTE,
    isNew: true,
    attributes: {
      _placeholder: 'sim',
      reference: 'VS-GM-004',
      movement: 'Automático',
      calibre: 'VS 3285',
      powerReserve: '70 horas',
      caseMaterial: 'Titânio grau 5',
      caseDiameter: 41,
      caseThickness: 12,
      crystal: 'Safira',
      waterResistance: '100 m',
      dialColor: 'Cinza ardósia',
      strap: 'Titânio',
      gender: 'Masculino',
      condition: 'Novo',
      boxAndPapers: 'Completo (caixa e certificado)',
      warranty: '2 anos Vellor',
    },
    weightGrams: 800,
    dims: [20, 16, 12],
    variants: [{ sku: 'VS-GM-004', name: 'Padrão', stockQuantity: 2 }],
  },
  {
    slug: 'calendario-perpetuo-platina',
    name: 'Calendário Perpétuo Platina',
    brand: 'Vellor Sélection',
    categorySlug: 'relogios',
    collectionSlug: 'alta-relojoaria',
    priceCents: 18_900_000,
    shortDescription: 'Grande complicação em platina 950 com fases da lua e fundo de safira.',
    description: PLACEHOLDER_NOTE,
    isFeatured: true,
    attributes: {
      _placeholder: 'sim',
      reference: 'VS-QP-005',
      movement: 'Automático',
      calibre: 'VS 240 Q',
      powerReserve: '48 horas',
      functions: 'Calendário perpétuo, fases da lua, ano bissexto',
      caseMaterial: 'Platina 950',
      caseDiameter: 39,
      caseThickness: 8.9,
      crystal: 'Safira',
      waterResistance: '30 m',
      dialColor: 'Azul',
      strap: 'Couro de jacaré azul',
      gender: 'Masculino',
      condition: 'Novo',
      boxAndPapers: 'Completo (caixa e certificado)',
      warranty: '2 anos Vellor',
    },
    weightGrams: 750,
    dims: [22, 18, 12],
    variants: [{ sku: 'VS-QP-005', name: 'Padrão', stockQuantity: 1 }],
  },
  {
    slug: 'dress-esqueleto-corda-manual',
    name: 'Dress Esqueleto Corda Manual',
    brand: 'Vellor Sélection',
    categorySlug: 'relogios',
    collectionSlug: 'classicos',
    priceCents: 2_780_000,
    shortDescription: 'Mecanismo esqueletizado à vista, decoração côtes de Genève.',
    description: PLACEHOLDER_NOTE,
    attributes: {
      _placeholder: 'sim',
      reference: 'VS-SK-006',
      movement: 'Corda manual',
      calibre: 'VS 1200 SQ',
      powerReserve: '42 horas',
      caseMaterial: 'Aço inoxidável',
      caseDiameter: 40,
      caseThickness: 8.5,
      crystal: 'Safira',
      waterResistance: '30 m',
      dialColor: 'Esqueletizado',
      strap: 'Couro preto',
      gender: 'Unissex',
      condition: 'Novo',
      boxAndPapers: 'Completo (caixa e certificado)',
      warranty: '2 anos Vellor',
    },
    weightGrams: 650,
    dims: [20, 16, 12],
    variants: [{ sku: 'VS-SK-006', name: 'Padrão', stockQuantity: 2 }],
  },
  {
    slug: 'cronografo-ouro-amarelo-18k',
    name: 'Cronógrafo Ouro Amarelo 18k',
    brand: 'Vellor Sélection',
    categorySlug: 'relogios',
    collectionSlug: 'ouro-e-metais-nobres',
    priceCents: 6_800_000,
    shortDescription: 'Cronógrafo em ouro amarelo maciço com mostrador champanhe.',
    description: PLACEHOLDER_NOTE,
    attributes: {
      _placeholder: 'sim',
      reference: 'VS-AU-007',
      movement: 'Automático com cronógrafo',
      calibre: 'VS 4131',
      powerReserve: '72 horas',
      caseMaterial: 'Ouro amarelo 18k',
      caseDiameter: 40,
      caseThickness: 12.2,
      crystal: 'Safira',
      waterResistance: '100 m',
      dialColor: 'Champanhe',
      strap: 'Ouro amarelo 18k',
      gender: 'Masculino',
      condition: 'Novo',
      boxAndPapers: 'Completo (caixa e certificado)',
      warranty: '2 anos Vellor',
    },
    weightGrams: 1100,
    dims: [20, 16, 12],
    variants: [{ sku: 'VS-AU-007', name: 'Padrão', stockQuantity: 1 }],
  },
  {
    slug: 'tourbillon-edicao-limitada',
    name: 'Tourbillon Edição Limitada',
    brand: 'Vellor Sélection',
    categorySlug: 'relogios',
    collectionSlug: 'alta-relojoaria',
    priceCents: 24_500_000,
    shortDescription: 'Tourbillon voador em série numerada de 50 peças.',
    description: PLACEHOLDER_NOTE,
    isNew: true,
    isFeatured: true,
    attributes: {
      _placeholder: 'sim',
      reference: 'VS-TB-008',
      movement: 'Tourbillon',
      calibre: 'VS 9500 T',
      powerReserve: '80 horas',
      functions: 'Tourbillon voador, reserva de marcha',
      caseMaterial: 'Ouro branco 18k',
      caseDiameter: 41,
      caseThickness: 10.5,
      crystal: 'Safira',
      waterResistance: '30 m',
      dialColor: 'Preto grand feu',
      strap: 'Couro de jacaré preto',
      gender: 'Masculino',
      condition: 'Novo',
      boxAndPapers: 'Completo (caixa e certificado)',
      warranty: '2 anos Vellor',
    },
    weightGrams: 800,
    dims: [22, 18, 12],
    variants: [{ sku: 'VS-TB-008', name: 'Padrão', stockQuantity: 1 }],
  },
  // ---------- Perfumes ----------
  {
    slug: 'oud-imperial-extrait',
    name: 'Oud Imperial Extrait',
    brand: 'Maison Vellor',
    categorySlug: 'perfumes',
    collectionSlug: 'orientais-e-ambar',
    priceCents: 249_000,
    shortDescription: 'Oud do Laos, rosa de Taif e açafrão em concentração extrait.',
    description: PLACEHOLDER_NOTE,
    isFeatured: true,
    isBestseller: true,
    attributes: {
      _placeholder: 'sim',
      concentration: 'Extrait de Parfum',
      olfactoryFamily: 'Oriental / Âmbar',
      topNotes: 'Açafrão, cardamomo',
      heartNotes: 'Rosa de Taif, oud',
      baseNotes: 'Âmbar, sândalo, almíscar',
      longevity: 'Muito longa',
      sillage: 'Intensa',
      perfumer: 'Perfumista da casa',
      origin: 'França',
      launchYear: '2024',
      gender: 'Unissex',
      sealed: 'Lacrado',
    },
    weightGrams: 450,
    dims: [16, 11, 10],
    variants: [
      { sku: 'MV-OUD-50', name: '50 ml', stockQuantity: 6, optionValues: { Volume: '50 ml' } },
      {
        sku: 'MV-OUD-100',
        name: '100 ml',
        priceCents: 389_000,
        stockQuantity: 4,
        optionValues: { Volume: '100 ml' },
      },
    ],
  },
  {
    slug: 'vetiver-sagrado-eau-de-parfum',
    name: 'Vetiver Sagrado Eau de Parfum',
    brand: 'Maison Vellor',
    categorySlug: 'perfumes',
    collectionSlug: 'amadeirados',
    priceCents: 159_000,
    shortDescription: 'Vetiver do Haiti, cedro e incenso em um amadeirado seco e elegante.',
    description: PLACEHOLDER_NOTE,
    attributes: {
      _placeholder: 'sim',
      concentration: 'Eau de Parfum',
      olfactoryFamily: 'Amadeirado',
      topNotes: 'Bergamota, pimenta rosa',
      heartNotes: 'Vetiver, cedro',
      baseNotes: 'Incenso, vetiver defumado',
      longevity: 'Longa',
      sillage: 'Moderada',
      perfumer: 'Perfumista da casa',
      origin: 'França',
      launchYear: '2022',
      gender: 'Masculino',
      sealed: 'Lacrado',
    },
    weightGrams: 500,
    dims: [16, 11, 10],
    variants: [
      { sku: 'MV-VET-100', name: '100 ml', stockQuantity: 8, optionValues: { Volume: '100 ml' } },
    ],
  },
  {
    slug: 'iris-absolue-extrait',
    name: 'Íris Absolue Extrait',
    brand: 'Maison Vellor',
    categorySlug: 'perfumes',
    collectionSlug: 'florais',
    priceCents: 295_000,
    shortDescription: 'Íris de Florença pura sobre um fundo de violeta e sândalo.',
    description: PLACEHOLDER_NOTE,
    isFeatured: true,
    attributes: {
      _placeholder: 'sim',
      concentration: 'Extrait de Parfum',
      olfactoryFamily: 'Floral',
      topNotes: 'Violeta, cenoura',
      heartNotes: 'Íris de Florença',
      baseNotes: 'Sândalo, almíscar branco',
      longevity: 'Longa',
      sillage: 'Discreta',
      perfumer: 'Perfumista da casa',
      origin: 'Itália',
      launchYear: '2023',
      gender: 'Feminino',
      sealed: 'Lacrado',
    },
    weightGrams: 450,
    dims: [16, 11, 10],
    variants: [
      { sku: 'MV-IRIS-75', name: '75 ml', stockQuantity: 5, optionValues: { Volume: '75 ml' } },
    ],
  },
  {
    slug: 'bergamota-riviera-cologne',
    name: 'Bergamota Riviera Cologne',
    brand: 'Maison Vellor',
    categorySlug: 'perfumes',
    collectionSlug: 'citricos-e-frescos',
    priceCents: 129_000,
    shortDescription: 'Bergamota da Calábria, neroli e um toque salino de brisa mediterrânea.',
    description: PLACEHOLDER_NOTE,
    attributes: {
      _placeholder: 'sim',
      concentration: 'Eau de Cologne',
      olfactoryFamily: 'Cítrico',
      topNotes: 'Bergamota, limão siciliano',
      heartNotes: 'Neroli, petitgrain',
      baseNotes: 'Almíscar, notas salinas',
      longevity: 'Moderada',
      sillage: 'Moderada',
      perfumer: 'Perfumista da casa',
      origin: 'Itália',
      launchYear: '2021',
      gender: 'Unissex',
      sealed: 'Lacrado',
    },
    weightGrams: 550,
    dims: [16, 11, 12],
    variants: [
      { sku: 'MV-BERG-100', name: '100 ml', stockQuantity: 10, optionValues: { Volume: '100 ml' } },
      {
        sku: 'MV-BERG-200',
        name: '200 ml',
        priceCents: 199_000,
        stockQuantity: 3,
        optionValues: { Volume: '200 ml' },
      },
    ],
  },
  {
    slug: 'ambar-noir-parfum',
    name: 'Âmbar Noir Parfum',
    brand: 'Maison Vellor',
    categorySlug: 'perfumes',
    collectionSlug: 'orientais-e-ambar',
    priceCents: 219_000,
    shortDescription: 'Labdanum, benjoim e baunilha negra em um âmbar denso para a noite.',
    description: PLACEHOLDER_NOTE,
    isBestseller: true,
    attributes: {
      _placeholder: 'sim',
      concentration: 'Parfum',
      olfactoryFamily: 'Oriental / Âmbar',
      topNotes: 'Pimenta preta, rum',
      heartNotes: 'Labdanum, benjoim',
      baseNotes: 'Baunilha negra, patchouli',
      longevity: 'Muito longa',
      sillage: 'Intensa',
      perfumer: 'Perfumista da casa',
      origin: 'França',
      launchYear: '2020',
      gender: 'Unissex',
      sealed: 'Lacrado',
    },
    weightGrams: 450,
    dims: [16, 11, 10],
    variants: [
      { sku: 'MV-AMB-50', name: '50 ml', stockQuantity: 7, optionValues: { Volume: '50 ml' } },
      {
        sku: 'MV-AMB-100',
        name: '100 ml',
        priceCents: 329_000,
        stockQuantity: 4,
        optionValues: { Volume: '100 ml' },
      },
    ],
  },
  {
    slug: 'sandalo-de-mysore-edp',
    name: 'Sândalo de Mysore Eau de Parfum',
    brand: 'Maison Vellor',
    categorySlug: 'perfumes',
    collectionSlug: 'amadeirados',
    priceCents: 189_000,
    shortDescription: 'Sândalo cremoso com cardamomo e leite de figo.',
    description: PLACEHOLDER_NOTE,
    attributes: {
      _placeholder: 'sim',
      concentration: 'Eau de Parfum',
      olfactoryFamily: 'Amadeirado',
      topNotes: 'Cardamomo, figo',
      heartNotes: 'Sândalo de Mysore',
      baseNotes: 'Leite de amêndoa, almíscar',
      longevity: 'Longa',
      sillage: 'Moderada',
      perfumer: 'Perfumista da casa',
      origin: 'Índia',
      launchYear: '2023',
      gender: 'Unissex',
      sealed: 'Lacrado',
    },
    weightGrams: 500,
    dims: [16, 11, 10],
    variants: [
      { sku: 'MV-SAND-100', name: '100 ml', stockQuantity: 6, optionValues: { Volume: '100 ml' } },
    ],
  },
  {
    slug: 'rosa-de-taif-extrait',
    name: 'Rosa de Taif Extrait',
    brand: 'Maison Vellor',
    categorySlug: 'perfumes',
    collectionSlug: 'florais',
    priceCents: 340_000,
    shortDescription: 'Rosa de Taif destilada à mão, lichia e almíscar.',
    description: PLACEHOLDER_NOTE,
    isNew: true,
    attributes: {
      _placeholder: 'sim',
      concentration: 'Extrait de Parfum',
      olfactoryFamily: 'Floral',
      topNotes: 'Lichia, pimenta rosa',
      heartNotes: 'Rosa de Taif, gerânio',
      baseNotes: 'Almíscar, âmbar cinza',
      longevity: 'Muito longa',
      sillage: 'Intensa',
      perfumer: 'Perfumista da casa',
      origin: 'Emirados Árabes',
      launchYear: '2025',
      gender: 'Feminino',
      sealed: 'Lacrado',
    },
    weightGrams: 450,
    dims: [16, 11, 10],
    variants: [
      { sku: 'MV-ROSA-50', name: '50 ml', stockQuantity: 4, optionValues: { Volume: '50 ml' } },
    ],
  },
  {
    slug: 'couro-veneziano-edicao-especial',
    name: 'Couro Veneziano Edição Especial',
    brand: 'Maison Vellor',
    categorySlug: 'perfumes',
    collectionSlug: 'extraits-e-edicoes-especiais',
    priceCents: 490_000,
    shortDescription: 'Couro, açafrão e íris em frasco numerado com tampa em latão.',
    description: PLACEHOLDER_NOTE,
    isNew: true,
    isFeatured: true,
    attributes: {
      _placeholder: 'sim',
      concentration: 'Extrait de Parfum',
      olfactoryFamily: 'Couro',
      topNotes: 'Açafrão, bergamota',
      heartNotes: 'Couro, íris',
      baseNotes: 'Bétula, âmbar, oud',
      longevity: 'Muito longa',
      sillage: 'Intensa',
      perfumer: 'Perfumista da casa',
      origin: 'Itália',
      launchYear: '2025',
      gender: 'Unissex',
      sealed: 'Lacrado',
    },
    weightGrams: 600,
    dims: [18, 12, 12],
    variants: [
      { sku: 'MV-COURO-100', name: '100 ml', stockQuantity: 2, optionValues: { Volume: '100 ml' } },
    ],
  },
];
